### ISSUE TITLE
Group warfare.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#102]
If you (player 2) attack someone (player 1) and then someone else (player 3) attacks them (player 1) both of you (players 1 and 2) should both lose troops.

**Comment by elthran** [comment]
The way the game is currently set up, this seems impossible (to do it in a fun way). After we get the game more finished in a month or so, then we will look into some ideas like this. I will clear this up from tickets for now as it would fit much better in some sort of discussion/idea wikipedia or forum, rather than a ticket of some task we need to do. If we were to do something like this, it would probably be an allied thing where you can send an attack proposal to an ally and it marks your troops as busy, and if your ally accepts then you both join forces and attack a larger player. But this stuff would be after we have alliances, kingdom rulers, castles, and way more features.
