### ISSUE TITLE
Send Scouts before attacking.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#131]
Scouts would report on military defensive strength (not just unit numbers).
Would be a button just like send Thieves but on attack page.
Would be an estimate like between 1000-1250 defensive strength.

**Comment by elthran** [comment]
@klondikemarlen I think I have a better idea for how to completely redo thieves. Right now you can occasionally scout a country and the more thieves guilds you have, the more accurate the data is. The problem is it's hard to scale/balance. 

My new idea: Thives guilds don't affect accuracy at all. Each thieves guild allows you to scout once a day (so thieves return after 24 hours or maybe a bit less). So the more thieves guilds, the more things you can scout (this scales nicely because the bigger your kingdom, the more things you'll need to scout). You will be able to scout many different things. You could scout a county's current resources, their current military strength, their buildings, etc. Maybe you could even send them on thief missions where they steal gold or burn crops. We could even have a % chance that they are caught and killed (then you must wait a few days to train new ones), or they could be discovered and then the county knows WHO scouted them.
