### ISSUE TITLE
is_authicated is wrong variable in advance_age()

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#142]
We need to log out all users bug using something other than is_authenticated.

**Comment by elthran** [comment]
Can you find a fix for this sometime this week? Even if the fix is just not logging out any users (I don't think that's a problem at all, since every user could stay logged in, their county would be deleted, and they would be redirected to 'initialize' page when the game detects they dont have a county). anything is better than now, where all users get locked out of their accounts at reset :D
