### ISSUE TITLE
Put a two day safety lock against attacking newly created accounts.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#155]
This is a player exploit, we should list somewhere that this will get you banned. And I should probably build in IP blacklisting as well.

**Comment by klondikemarlen** [comment]
Perhaps to make this better for new players, allow new players to attack each other but not let old players attack them for at least 2 days.

**Comment by klondikemarlen** [comment]
My suggestion invovles and "age difference" timelock.

To prevent new players from being farmed by old players. And to fit in lore ... make new players invisible to older players. Basically you haven't heard that a new county has sprung up.

**Comment by elthran** [comment]
This exploit is pretty diminished after patching #152 as soon a you grow a little past 150 acres, you won't really gain much by attacking new accounts. And if you are only at 150 acres, I don't really care if you attack a new account once (once we make it so that new accounts can't send all your defensive power out, attacking a new account is basically the same as attacking any other player at 150 acres)

**Comment by elthran** [comment]
I will close this for now since it's not really an exploit anymore in the current state of the game. I think thieves would be more exploitable than military at this point, since you could create a new account, put everything into thievery buildings, and the next day absolutely wreck someone with all your thieves doing full damage. I will think of some way to thematically limit this.
