### ISSUE TITLE
Prevent suicide attacks.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#156]
Your troops should refuse to attack if you are vastly outnumbered. You could then be deposed and executed by your populace :)

**Comment by klondikemarlen** [comment]
Basically add auto-banning into game lore.

**Comment by elthran** [comment]
This makes no sense to me, so I must be misunderstanding what the exploit. In my mind, the exploit is "I want player x to lose, so I create extra accounts and use them to immediately attack player x and then delete my account or ignore it". This doesn't seem to stop the exploit. We need a way to limit offensive power for new accounts. I would recommend not allowing counties to attack with all their troops. Eg. you start the game with 50-75 troops but when you go to the attack page it says "you must leave at least 50 troops to guard your county". That or add the garrisson feature I was working on last week which would completely void this exploit :P

**Comment by elthran** [comment]
After some testing, I would propose adding a new battle result:
- Closely matched (Very similar power. You gain about half the land / they lose half the land). Both Somewhat happy
- Minor victory / Minor defeat (Normal)
- Major victory / Major defeat (Normal but with extra casaulties for the losing player)
-  Massacre: The enemy fled in terror (if you are the winner - there are basically no casaulties and due to the new reward system you would gain basically nothing. Your army would return quite quickly)
- Quickly Routed: Your army quickly flees in terror after seeing the enemy's forces (if you attack and are very badly outnumbered - you would only lose 1 or two troops and your army would return very quickly) 

This should basically resolve the exploit while being super simple, easy to code, and fit thematically

**Comment by klondikemarlen** [comment]
Sounds excellent!

**Comment by klondikemarlen** [comment]
I think you (@elthran) fixed this? I can't find the commit to reference, if you don't mind would you add that in before closing it?
