### ISSUE TITLE
Consider making attacks delayed by x turns.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#81]
I think it might be interesting to delay attacks.
That way you could get a notification that someone is attacking you but is 2 (or 1-4) days away. You could then put forth your best effort to conscript some extra soldiers.

**Comment by elthran** [comment]
This is another one I'm going to close as a ticket (since it's not something that needs to get done yet) and move it to the discussion channel, since it's an idea that might get implemented and will likely get discussed before hand. But I think it goes against game psychology to delay the results of a battle by hours (you can delay the land being received, but if a player has to log in the next day to find out how they did, the battle loses a lot of its fun and excitement).
