### ISSUE TITLE
Too few relevant actions per turn.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#83]
I suggest attempting to level the game so as to allow 4 relevant actions per turn.
For example, building 2 buildings, building 20 troops and attacking.

The game needs a progression control such that you can do a similar amount no matter what turn of the game you are on. Or at least you go from 1-2 to 2-3 to 4-6 relevant actions per turn.

Relevant action means if you have 300 buildings then building 4-6 might be relevant. Whereas, if you had 300 troops building 5 wouldn't be relevant, but building 10-20 would be.

**Comment by elthran** [comment]
I am not 100% what you mean here? But I would kind of wait until we haev more features (thieves, magic, pillaging, raiding, allies) and stuff before we start worrying about stuff like this, since we have no way to tell how busy we will be in the real game. I will close this since it's not really an actual ticket of things to do, and we can continue with it in something like #99
