### ISSUE TITLE
Live gameplay mode.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#85]
I suggest making days in the game equal to 5 minutes over a given period. That way it would be a lot more like live gameplay. Sort of a tournament mode? The game would be live for a 6 hour period? Then switch pause until the next live event. I propose making this a user choice and having multiple servers/version of the game.

**Comment by elthran** [comment]
If you want to do this, then go for it! It would not be difficult with the way the game is set up (everything right now is attached to world1 so you could create a world2 and have a new scheduler just hit it and have special accounts that have counties in this world.
I don't really see that it will benefit us enough to spend the few hours setting it up since I do'nt personally have time to play/test on a 5 minute/turn server, and I don't even think the data from it would be that useful since it would be artificial data.
So I will leave this 100% to you if you want to close it or try and build it. If you build it I can test on it as well (I would use it) when I have time.
